quarkus:
  application:
    name: qakrud

  log:
    level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
      level: DEBUG
      darken: 1

  quinoa:
    ui-root-path: app
    package-manager-install:
      ~: true
      node-version: 20.16.0

  jackson:
    serialization-inclusion: non-empty

  smallrye-openapi:
    info-title: QAKrud API
    info-description: This API allows CRUD operations on various resources
    info-version: 1.0
    info-contact-name: Quarkus
    info-contact-url: https://github.com/quarkusio

"%dev":
  quarkus:
    datasource:
      username: quarkus
      password: quarkus
      db-kind: postgresql
      db-version: 16.0
      reactive:
        url: postgresql://localhost:5432/qakrud
        max-size: 20
    hibernate-orm:
      sql-load-script: import-dev.sql
      database:
        generation: drop-and-create
      log:
        sql: false
    log:
      category:
        "com.opchaves":
            level: DEBUG

"%test":
  quarkus:
    datasource:
      devservices:
      username: quarkus
      password: quarkus
      db-kind: postgresql
      db-version: 16.0
      reactive:
        url: postgresql://localhost:5432/qakrud_test
        min-size: 2
        max-size: 8
    hibernate-orm:
      sql-load-script: import-test.sql
      database:
        generation: drop-and-create
      log:
        sql: false
